const EXPLOSION_MAX_RADIUS = 8;
const GREEN_DECREASE_MULTIPLIER = 0.95;
const BLUE_DECREASE_MULTIPLIER = 0.4;
const RED_DECREASE_MULTIPLIER = 0.98;
const ALPHA_DECREASE_MULTIPLIER = 0.99;

export class Explosion {
  
}
